trigger:
  branches:
    include:
      - master
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'TODO_APP_ACR_SERVICE_CONNECTION'
  imageRepository: 'todowebapp'
  containerRegistry: 'TODO_APP_ACR_NAME.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  azureSubscription: 'TODO_APP_AZURE_SERVICE_CONNECTION'
  webAppName: 'todowebapp'

stages:
  - stage: BuildDocker
    displayName: 'Build Docker Image'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        steps:
          - task: Docker@2
            displayName: 'Build Docker Image'
            inputs:
              command: 'build'
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

          - task: Docker@2
            displayName: 'Push to Container Registry'
            inputs:
              command: 'push'
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest

  - stage: DeployContainer
    displayName: 'Deploy Container'
    dependsOn: BuildDocker
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to Azure'
        environment: 'Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy Container to App Service'
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appName: '$(webAppName)'
                    containers: '$(containerRegistry)/$(imageRepository):$(tag)'